name: deploy-to-pages

on:
  push:
    branches: 
      - master

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: zhujunxi/view-ui_template@master

    - name: Build and Deploy
      uses: zhujunxi/view-ui_template@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: yarn install && yarn build
